Slr#01
MCastegnaro/super-logica-react pull request #5
Opened 2021-11-08 18:45 UTC by msalarini

2021-11-08 18:49 UTC, guilhermeafonsomb commented
trocar o titulo ou adicionar um comentario para informar o que esta sendo feito só "Slr#01" é vago

2021-11-08 19:28 UTC, guilhermeafonsomb requested changes

2021-11-08 19:28 UTC, guilhermeafonsomb commented on src/pages/home/index.tsx
> +import {
mudar o meio de importação para "import * as nomedoarquivo"

2021-11-08 19:28 UTC, guilhermeafonsomb commented on src/pages/home/styles.ts
> +`;
aproveitar mais o styled component, nao precisa criar tantos componentes assim. Seleciona os componentes principais e usa style cascat para elementos menores dentro do componente criado

2021-11-08 19:28 UTC, guilhermeafonsomb commented on src/index.css
> +}
como é um arquivo de style glocal, de esse nome para ele, referenciando que é o estilo global da aplicação. Você pode até fazer as variáveis de cor para usar durante toda a aplicação.

2021-11-08 19:29 UTC, guilhermeafonsomb commented
trocar o titulo ou adicionar um comentário para informar o que esta sendo feito só "Slr#1" é vago

2021-11-09 19:54 UTC, msalarini commented on src/pages/home/index.tsx
> +import {
Feito :white_check_mark:

2021-11-09 19:54 UTC, msalarini commented on src/pages/home/styles.ts
> +`;
Feito :white_check_mark:

2021-11-09 19:54 UTC, msalarini commented on src/index.css
> +}
Feito :white_check_mark:

2021-11-10 12:31 UTC, guilhermeafonsomb approved these changes

2022-04-19 00:32 UTC, merged